Fix action to pass if no changes in dependencies
ossillate-inc/packj-github-action pull request #4
Opened 2023-01-27 06:47 UTC by KhoiUna

```yaml
   - name: Detect changed dependencies
      shell: bash
      run: |
        passed=false        
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do          
          if [[ $file == *"package.json"* ]] || [[ $file == *"Gemfile"* ]] || [[ $file == *"requirements.txt"* ]]; then
              passed=true
          fi
        done
        echo $passed
        echo "CHECK_PASSED=$passed" >> $GITHUB_ENV
```

2023-01-31 15:09 UTC, ashishbijlani requested changes

2023-01-31 15:09 UTC, ashishbijlani commented on action.yaml
> +          if [[ $file == *"package.json"* ]] || [[ $file == *"Gemfile"* ]] || [[ $file == *"requirements.txt"* ]]; then
makes an assumption on the names of deps file. what if a user has reqs.txt as the dep file. we need to filter based on DEPENDENCY_FILES input.

2023-01-31 15:09 UTC, ashishbijlani commented on action.yaml
>          input=$(echo "${{ inputs.DEPENDENCY_FILES }}" | sed 's/,/ /g')
we are parsing deps file multiple times: first at line 45 name: Parse dependency files then again at line 101. We could store the output in ENV and reuse here.

2023-02-03 05:51 UTC, KhoiUna commented
I have made some updates!

2023-02-07 06:19 UTC, ashishbijlani requested changes

2023-02-07 06:19 UTC, ashishbijlani commented on action.yaml
> +
I think you were testing something with this code. Let's fix this. Rest looks good.

2023-02-07 15:20 UTC, ashishbijlani approved these changes

2023-02-16 15:48 UTC, merged